# Built with Flutter 3.38.5 (Mac Apple M1), Dart 3.10.4, CocoaPods 1.16.2, Xcode 26.2
name: guap_mobile
description: Mobile version of GUAP application
version: 1.5.7+26

environment:
  sdk: ">=3.10.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: 2.0.2                       # tuples support
  optional: 6.1.0+1                  # options support
  intl: 0.20.2                       # formatting messages
  http: 1.6.0                        # http client
  crypto: 3.0.7                      # SHA-256
  shared_preferences: 2.5.4          # key-value storage
  flutter_redux: 0.10.0              # redux
  redux_thunk: 0.4.0                 # redux thunk middleware
  json_annotation: 4.9.0             # json auto-generation
  flutter_slidable: 4.0.3            # dismissible list tiles (3.0.0 doesn't work)
  flutter_treeview2: 1.0.0+2         # fork of flutter_treeview, which is broken now
  flutter_typeahead: 5.2.0           # auto-complete textbox
  flutter_rounded_date_picker: 3.0.4 # calendar
  rflutter_alert: 2.0.7              # pop-ups

dev_dependencies:
  build_runner: 2.10.4               # json auto-generation
  json_serializable: 6.11.3          # json auto-generation

dependency_overrides:
  win32: 5.5.4                       # TMP: error "UnmodifiableUint8ListView not found in win32-4.1.4" (2025-12), rm once fixed

flutter:
  uses-material-design: true
